### ISSUE TITLE
Display tests/variants outside the terminal, as well

### ISSUE THREAD

**Issue by privateducky** [preludeorg/build#160]
It would be nice to see the tests+variants outside of the terminal. 

Let's copy the 'verified' sidebar into a new 'tests' sidebar, which shows all security tests and variants.

**Comment by stephanwampouille** [comment]
Should I re-use a design or could we have @NewMediaStudio do a mockup of what it would look like? For now I can work on the func.

**Comment by privateducky** [comment]
> Should I re-use a design or could we have @NewMediaStudio do a mockup of what it would look like? For now I can work on the func.

Offhand, I'd reuse the verified section and put the tab next to it, in the bottom right.
