### ISSUE TITLE
Add syntax / linter support per language

### ISSUE THREAD

**Issue by privateducky** [preludeorg/build#161]
The Build ui currently applies a linter to our custom test syntax. We also need to support basic syntax / linter support for the base languages themselves so that mistakes while writing code are reflected in the editor.

**Comment by mireaulf** [comment]
Spike done by @kenrick https://gist.github.com/kenrick/cda2c369a4d837c6d3907689f69656e7

**Comment by privateducky** [comment]
closing; we need to finalize the scoping of https://github.com/preludeorg/roadmap/issues/76 and I believe this ticket will fall out of scope.
