### ISSUE TITLE
Bugs in master branch only

### ISSUE THREAD

**Issue by privateducky** [preludeorg/build#207]
- there is a lock on my custom/created test (variant) on the tab
- "opened variant in readonly mode" should be "read-only"
- when opening a locked variant, I get the 'changes will auto save' toast message
- can we use a lock icon that has no design elements to it? it's so small, the shadow on the left side of the lock looks important but is not.

**Comment by kenrick** [comment]
Going to promote the lock icon issue to @NewMediaStudio. Just to clarify can we get a version of the lock icon with the 3 dots to the inside left.

**Comment by kenrick** [comment]
https://github.com/preludeorg/build/pull/212 Fixes the icon issue
