### ISSUE TITLE
unable to modify files in the code editor

### ISSUE THREAD

**Issue by VVX7** [preludeorg/build#237]
Tests cannot be modified in the editor.  After saving, a few chars from the input will be saved to the start of the file.

Repo:
- create new test
- create new variant
- attempt to edit the test 

![CleanShot 2022-12-15 at 07 33 03](https://user-images.githubusercontent.com/46228229/207860742-3a02ccb4-6db9-411f-b269-fad00cbca89d.png)

**Comment by kenrick** [comment]
@VVX7 This issue should be resolve on prod
