### ISSUE TITLE
Change "Create a handle" menu item wording

### ISSUE THREAD

**Issue by nsreidy2** [preludeorg/build#273]
The "user settings" menu (in the upper-right) lists four things: the handle, the account ID, and two actions: "Create a handle" and "Import credentials".

Please rename the "Create a handle" action item to "Save tests to your account"

**Comment by kenrick** [comment]
@nsreidy2 We are also noodling on calling it "Register an account". Thoughts here @privateducky @khyberspache ?

**Comment by nsreidy2** [comment]
To me, "register an account" is like "create a handle" inasmuch as the user won't necessarily know why he/she wants to do that.

"Save tests to your account" (or a similar phrase) is intended to convey the "why" rather than just the "what."

**Comment by privateducky** [comment]
yeah; we're converting some language to 'register account' instead of 'create a handle' -- but also looking at a top nav bar that adds explainer text as to why you would want to do this.
