### ISSUE TITLE
change wording to unpack what a VST is

### ISSUE THREAD

**Issue by nsreidy2** [preludeorg/build#293]
current wording for Deploy Test popup is
"Click here to generate a url for the VST then click the copy button to copy the url to your clipboard."

desired wording is
"Click here to generate a url for the VST (Verified Security Test) then click the copy button to copy the url to your clipboard."

(the aim is to define an acronym when the user is or may be seeing it for the first time)

**Comment by kenrick** [comment]
Can you take this one @stephanwampouille
