### ISSUE TITLE
Support uploading arbitrary files to a test

### ISSUE THREAD

**Issue by privateducky** [preludeorg/build#305]
Depends on API and SDK updates here: https://github.com/preludeorg/libraries/issues/192

The UI should support test attachments.

**Comment by kenrick** [comment]
This is done

**Comment by privateducky** [comment]
> This is done

Is this on the master branch of Build/in staging?

**Comment by kenrick** [comment]
Yes, this is the ability to get the test attachments correct? Eg the test README.md?

**Comment by privateducky** [comment]
ah - no.
this ticket is a child to https://github.com/preludeorg/roadmap/issues/75, where the goal is to support arbitrary file uploads.

**Comment by kenrick** [comment]
OK reopening
