### ISSUE TITLE
Work on color scheme of Build/Demo pages

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#351]

**Comment by kenrick** [comment]
@privateducky could you elaborate some more on this one. What the currently issues with the color schemes between build and demo pages?

**Comment by privateducky** [comment]
@sthomps this is your neck of the woods ;)

**Comment by sthomps** [comment]
will work with @NewMediaStudio on this!

**Comment by privateducky** [comment]
Closing, as we didn't get it done during the sprint week.
