### ISSUE TITLE
Move the build results and VSTs to from the sidebar

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#354]

**Comment by kenrick** [comment]
Rule
 |___Test
           |___Builts

**Comment by kenrick** [comment]
Rule -> Test -> Compiled files

**Comment by kenrick** [comment]
@NewMediaStudio You can go ahead and mock this up so we can see if it makes sense.

**Comment by NewMediaStudio** [comment]
I like that idea. On it.

**Comment by NewMediaStudio** [comment]
Let me know what you think:

[Prototype](https://www.figma.com/proto/DaXnmU0nwElQ16fZ7MIotE/Platform?node-id=1569%3A26943&viewport=1511%2C-1227%2C0.52&scaling=min-zoom&starting-point-node-id=1569%3A27974&show-proto-sidebar=1)

[Zeplin](https://zpl.io/W4Pv4Bk)

<img width="459" alt="Screenshot 2023-01-19 at 4 35 52 PM" src="https://user-images.githubusercontent.com/15107444/213567368-6188c9b1-e2b8-4a44-aecc-abc921ddba34.png">

For compiled - are you thinking of using the status area below? I thought we could show table there that can be toggled or not (console style).

To create a new security test I think we can either house individual adds in a tree (or have a global one that adds an extra inline step with a dropdown).

**Comment by kenrick** [comment]
I like the test icon 👍 . This looks great overall. Lets get @stephanwampouille and @privateducky eyes on this as well

**Comment by kenrick** [comment]
@NewMediaStudio for the test's wont have names just a filename eg. `890c28fd-d866-407b-918b-83bbc26cb48d.go`

**Comment by privateducky** [comment]
these look great! 
and yep; we'll be starting with just the IDs as the names and will update to plain-text names once we have that support.

**Comment by stephanwampouille** [comment]
Just seeing this now, but looks good!
