### ISSUE TITLE
Give the Rule more prominent treatment

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#355]
On the demo experience page we want to make the rule of the test more prominent. 

<img width="1031" alt="Screenshot 2023-01-17 at 12 14 42 PM" src="https://user-images.githubusercontent.com/760470/212991226-400d4824-957d-479a-b39d-04d91c33b2ab.png">

**Comment by kenrick** [comment]
@NewMediaStudio any ideas how we can address this?

**Comment by NewMediaStudio** [comment]
What about something like this?

<img width="972" alt="Screenshot 2023-01-17 at 2 28 06 PM" src="https://user-images.githubusercontent.com/15107444/212993984-ed8248d0-d3ef-41dd-9070-c7aaf79a6643.png">

As these gain clarity we can introduce consistent tags/icons for common concepts like "probe", "rule", "test"

**Comment by NewMediaStudio** [comment]
[[[](url)](https://www.figma.com/file/DaXnmU0nwElQ16fZ7MIotE/Platform?node-id=1145%3A19593&t=RJ2M5VHJMAWdKOpp-1)](https://www.figma.com/file/DaXnmU0nwElQ16fZ7MIotE/Platform?node-id=1145%3A19593&t=RJ2M5VHJMAWdKOpp-1)

**Comment by kenrick** [comment]
Hmm, the green around the "Rule" is a bit muted.

**Comment by kenrick** [comment]
cc @sthomps your eyes on this would be good too

**Comment by sthomps** [comment]
sure thing

**Comment by NewMediaStudio** [comment]
@kenrick We're exploring a new treatment for homepage, will update this one too :)

**Comment by NewMediaStudio** [comment]
@sthomps @kenrick What do you think about this, bringing it closer to what we have on the homepage with a consistent lockup (when we have our inverse theme it'd look closer to homepage):

https://zpl.io/RMv6GGn

<img width="1078" alt="Screenshot 2023-01-20 at 12 33 09 PM" src="https://user-images.githubusercontent.com/15107444/213765618-e4e07f39-39cd-4db1-b5bc-5408e9603bc1.png">

I also introduced a different icon for rule that's more "authoritative"

**Comment by NewMediaStudio** [comment]
For reference: https://prelude-com.webflow.io/home-update (pw: bagel)

**Comment by sthomps** [comment]
yep better

Spencer Thompson

Founder
Sokanu
***@***.***
604.349.1256
