### ISSUE TITLE
Demo flow not clear on probe name

### ISSUE THREAD

**Issue by privateducky** [preludeorg/build#376]
If you create a new probe in the demo experience, run the install script (any OS), and look back in the app... you'll have two probes - unless you had the foresight to name your probe the same in both places.

**Comment by kenrick** [comment]
@privateducky Are these the steps to repo:
1. Click the OS button to get the command
2. Create a probe in the sidebar
3. Copy & Run the command in the from the probe page

**Comment by privateducky** [comment]
slight variance:

1. Click the OS button to get the command
2. Create a probe in the sidebar
3. Copy & Run the command in the from the probe page
4. Run demo. Choose to install probe within script when prompted.
5. Note second probe

**Comment by privateducky** [comment]
btw -- one argument, is that this is intentional behavior, in need of better UX

**Comment by kenrick** [comment]
@privateducky Understood, also spoke with @FM & @makk94. Looks like we can update the demo script to just reuse the `token` by passing it to the install script. Removing the need to change the script on the UI.
