### ISSUE TITLE
Add install script to probe page

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#393]

**Comment by kenrick** [comment]
@FM Can you put an example of the install script in this ticket

**Comment by mireaulf** [comment]
Windows: `Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted; Invoke-WebRequest -UseBasicParsing -Uri 'PRELUDE_API/download/install' -Headers @{'token'=TOKEN;'dos'='windows-x86_64'} -OutFile "$env:TMP\install.ps1"; "$env:TMP\install.ps1 ACCOUNT_ID ACCOUNT_TOKEN" | Invoke-Expression`

Darwin: `curl -sSL "PRELUDE_API/download/install" -H "token:TOKEN" -H "dos:darwin-x86_64" > install.sh && chmod +x install.sh && ./install.sh ACCOUNT_ID ACCOUNT_TOKEN`

Linux:  `curl -sSL "PRELUDE_API/download/install" -H "token:TOKEN" -H "dos:linux-x86_64" > install.sh && chmod +x install.sh && ./install.sh ACCOUNT_ID ACCOUNT_TOKEN`
