### ISSUE TITLE
Build is not import credentials for non Admin users

### ISSUE THREAD

**Issue by privateducky** [preludeorg/build#414]

**Comment by kenrick** [comment]
it shouldn't be if its not working on other users this is a bug

**Comment by privateducky** [comment]
ok. might be a bug.

**Comment by kenrick** [comment]
When we import a user's credentials the UI looks for the user's handle by making a request to `getUsers` and using the first user in the list. The problem current is `/iam/user` is only accessible by `admin` users so this blocks other users from completing the import feature.

Once we allow non-admin users to request `/iam/user` we also need a way to to map the handle to the user making the request.

This could mean adding an api route to get the current user or adding a field to the current user in the list returned from `/iam/user`
eg
```
[ 
 {
  "handle": "admin-user",
  "permission": 0
 },
 {
 "handle": "build-user"
 "permission": 1
 "current": true
 }
]
```
This way the UI knows which item in the array to use
cc @privateducky @mireaulf

**Comment by gerbsec** [comment]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/67713732/215816368-ef4eb9c3-1a00-43a5-83e5-b0b33a50d8cd.png">

Confirming this is still happening.
