### ISSUE TITLE
Update demo experience windows CLI

### ISSUE THREAD

**Issue by mireaulf** [preludeorg/build#416]
Relates to https://github.com/preludeorg/test/issues/44

`Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted; Invoke-WebRequest -UseBasicParsing -Uri **API_URL** -Headers @{'token'=**TOKEN**;'dos'='windows-x86_64'} -OutFile "$env:TMP\demo.ps1"; "$env:TMP\demo.ps1 **TOKEN**" | Invoke-Expression`

**Comment by kenrick** [comment]
Change
`-OutFile 'demo.ps1'; .\demo.ps1 TOKEN`
to
`-OutFile '$env:TMP\demo.ps1'; '$env:TMP\demo.ps1 TOKEN' | Invoke-Expression`

**Comment by mireaulf** [comment]
It needs to be double quotes
-OutFile "$env:TMP\demo.ps1"; "$env:TMP\demo.ps1 TOKEN" | Invoke-Expression

**Comment by kenrick** [comment]
Done
