### ISSUE TITLE
Point https://staging.preludesecurity.com to webflow

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#453]
With our demo experience now living on the homepage it's necessary to make sure we can test the flow before pushing to production. To do this we need to simulate the production env a closely as possible by:

- [x] Adding a entry to webflow for https://staging.preludesecurity.com and providing the IP address @NewMediaStudio 
- [ ] Add a DNS record for that staging.preludesecurity.com pointing to that IP address @packplusplus

**Comment by NewMediaStudio** [comment]
@packplusplus Can you please point staging.preludesecurity.com to the following:

CNAME | staging | proxy-ssl.webflow.com
TXT | @ | proxy-ssl.webflow.com

**Comment by kenrick** [comment]
Thanks for the quick turnaround on this @packplusplus @NewMediaStudio. You guys are awesome
