### ISSUE TITLE
Add rule selector UI component

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#460]
Add the rule selector UI component seen here:
<img width="414" alt="Screenshot 2023-01-30 at 1 55 48 PM" src="https://user-images.githubusercontent.com/760470/215593583-fd26fbf9-00d1-4c1c-9acd-db59a2f1af03.png">

These will be clickable and when selected will look like 
<img width="746" alt="Screenshot 2023-01-30 at 2 00 12 PM" src="https://user-images.githubusercontent.com/760470/215593792-9954ab1f-fa8f-48c7-ae2e-a476b0f44d6e.png">

When the close is clicked it will return to the list form.

**Comment by stephanwampouille** [comment]
So this will show all rules applicable to a user, even self created ones? Do the numbers next to the icons signal the amount of tests under that rule? What does the rule button with the accordion on the lefthand side (second picture) do?

**Comment by NewMediaStudio** [comment]
@stephan Great questions - the numbers and colours are meant to indicate the "types" of rules, kind of like [the periodic table](https://www.google.com/search?q=periodic+table&rlz=1C5CHFA_enCA974CA974&oq=period&aqs=chrome.0.35i39i67j69i57j0i512l2j0i131i433i512j46i131i433i512j0i512j69i60.1502j0j7&sourceid=chrome&ie=UTF-8)

I'm going to work with @privateducky and @sthomps to work out the exact categories and rules.

I added some elements there that could potentially help navigate between the rules and apply them as filters to the user views.

**Comment by NewMediaStudio** [comment]
@privateducky @sthomps Do we have a draft list of future rules somewhere? Maybe we can start a list somewhere and attempt to categorize the rules?

**Comment by privateducky** [comment]
> @privateducky @sthomps Do we have a draft list of future rules somewhere? Maybe we can start a list somewhere and attempt to categorize the rules?

Yep; here: https://docs.google.com/spreadsheets/d/1RtRYW5_gMTgpS949dJUOnjvMiAJ9KWb5Uo8BxZStv2M/edit

**Comment by privateducky** [comment]
Each rule is categorized into 1 of 3 parts of the operating system
