### ISSUE TITLE
Add Questions section to Filter Sidebar

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#463]
<img width="305" alt="Screenshot 2023-01-30 at 2 12 07 PM" src="https://user-images.githubusercontent.com/760470/215596084-3c1c1b51-df78-47dd-9957-953d99290b6e.png">

**Comment by kenrick** [comment]
@privateducky just to clarify these are just tests correct?

**Comment by privateducky** [comment]
> @privateducky just to clarify these are just tests correct?

No... you should use the tests returned from the API...
