### ISSUE TITLE
Add Decision/Host Switcher and Date Range

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#464]
<img width="207" alt="Screenshot 2023-01-30 at 2 16 38 PM" src="https://user-images.githubusercontent.com/760470/215597006-f82f9c2b-cc6a-4b11-9df0-1f17245ab263.png">
<img width="1123" alt="Screenshot 2023-01-30 at 2 18 16 PM" src="https://user-images.githubusercontent.com/760470/215597248-094bb4fd-2d00-4cf1-af86-81754871e7a7.png">

**Comment by stephanwampouille** [comment]
should be able to move this to done, correct @kenrick

**Comment by kenrick** [comment]
yep!
