### ISSUE TITLE
Add the Decision Overlay 

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#468]
<img width="414" alt="Screenshot 2023-01-30 at 2 25 31 PM" src="https://user-images.githubusercontent.com/760470/215598737-52abf8f8-c3b3-4d06-a9a9-f99b1235acad.png">

 This will slide in the from the left when you select a Decision

**Comment by stephanwampouille** [comment]
PR: https://github.com/preludeorg/build/pull/491
