### ISSUE TITLE
Add Endpoint Overlay

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#469]
<img width="407" alt="Screenshot 2023-01-30 at 2 27 41 PM" src="https://user-images.githubusercontent.com/760470/215598983-122a79e5-1cbc-47a6-b3d2-a684111f6e5f.png">
This will slide in the from the right when selecting a host

**Comment by stephanwampouille** [comment]
done as well with my latest PR that was merged. just want to confirm @kenrick
