### ISSUE TITLE
Demo -> Platform connection is brittle

### ISSUE THREAD

**Issue by privateducky** [preludeorg/build#471]
If you go to preludesecurity.com and run our demo, then head to platform.preludesecurity.com, you will only see the results populate in specific scenarios -- primarily if you have never visited the app before / you aren't logged into it.

Expected: even if you are logged into the app, when you run the demo script it should be associated to your account.

**Comment by kenrick** [comment]
We can switch to cookies (client-side) from localstorage. so the domains can access the same credentials

**Comment by privateducky** [comment]
great work!
