### ISSUE TITLE
clicking on result for a test i created gives error

### ISSUE THREAD

**Issue by makk94** [preludeorg/build#479]
Repro:
1) Create your own test on Build
2) Run it & save results
3) Can see the results in the list section
![Screen Shot 2023-01-31 at 7 44 43 AM](https://user-images.githubusercontent.com/9056078/215807566-d5280cdf-27e2-4a10-add5-7815d59a5554.png)
4) Clicking on the MAHINA row gives the error page
![Screen Shot 2023-01-31 at 7 43 45 AM](https://user-images.githubusercontent.com/9056078/215807256-87c6ddd6-56f4-4689-b17e-39a0a0ccc419.png)

Ideal: I assume this comes from not being able to find the test/README in github. I think I do have a README attached to this test and it'd be nice to show that when I click on the MAHINA row

**Comment by mireaulf** [comment]
You **think** you have a README attached? Can you make sure so that we can repro appropriately.

**Comment by makk94** [comment]
ooo I actually just called mine README, and not README.md :/  moved it to README.md and it shows up as expected!

So maybe just a better error page/ restrict the error to the readme box and keep showing the rest of the page if there's no README.md?

**Comment by gerbsec** [comment]
Since it's not handling failure gracefully, tagging as bug as per davids comment

**Comment by stephanwampouille** [comment]
so to double check, you created a test on build then deployed that test against a probe then clicked on the result? @makk94

**Comment by makk94** [comment]
yep!
