### ISSUE TITLE
weird account permissions bug

### ISSUE THREAD

**Issue by gerbsec** [preludeorg/build#482]
Logging in as the sub-user "internal-waseem" from robins accounts results in this: 

<img width="422" alt="image" src="https://user-images.githubusercontent.com/67713732/215827199-a19f6fa2-e364-4d72-a845-e0c50af2a0b7.png">

Note: that I was upgraded to admin before doing that, we know #414 exists so I wasn't able to login before the upgrade

![image](https://user-images.githubusercontent.com/67713732/215827346-8e43cf33-5106-450a-b9c3-cd406f232547.png)

**Comment by kenrick** [comment]
Duplicate of https://github.com/preludeorg/build/issues/414

**Comment by mireaulf** [comment]
Closed as duplicate
