### ISSUE TITLE
Activity won't query after disabling and deleting a test

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/build#506]
<img width="992" alt="image (1)" src="https://user-images.githubusercontent.com/54591490/216437408-25d8c280-893d-422d-ad0e-062b8109d1a9.png">

This issue impacts cli as well.

<img width="424" alt="Screenshot 2023-02-02 at 3 03 54 PM" src="https://user-images.githubusercontent.com/54591490/216437680-0feb6cc7-d478-4c68-b4fa-f5755fbd149b.png">

**Comment by makk94** [comment]
@khyberspache @privateducky 
Any opinion on if we can tombstone tests when they're deleted so we can keep returning names in results vs just throwing in 'UNKNOWN' or 'DELETED' if the test name doesnt exist anymore

**Comment by privateducky** [comment]
Yeah, this should be handled client side.. showing DELETED sounds appropriate to me. Can't think of another scenario that could happen.
