### ISSUE TITLE
 Handle and account ID are cut off

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#511]

**Comment by kenrick** [comment]
<img width="238" alt="Screenshot 2023-02-03 at 2 19 11 AM" src="https://user-images.githubusercontent.com/760470/216536785-77bcb239-44ae-41ed-9ec0-d0db3d5d2f61.png">
@privateducky  is it preferred to line brake it?
<img width="332" alt="Screenshot 2023-02-03 at 2 20 31 AM" src="https://user-images.githubusercontent.com/760470/216537050-56b053f1-c8aa-4c48-ba0c-0429be41eeab.png">
or widen it width

**Comment by privateducky** [comment]
Line break looks a bit odd

**Comment by kenrick** [comment]
@ceci21  we are going with this version
![](https://user-images.githubusercontent.com/760470/216537050-56b053f1-c8aa-4c48-ba0c-0429be41eeab.png)
