### ISSUE TITLE
Show the DOS of the probe

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#514]
Results include the DOS of a probe. We should show this a) in the probe list and b) on each probe page.

**Comment by kenrick** [comment]
@privateducky I see the DOS in the activity but not the probes. We just checking  for the last activity's DOS to tell which OS the probe is running on

**Comment by privateducky** [comment]
> @privateducky I see the DOS in the activity but not the probes. We just checking  for the last activity's DOS to tell which OS the probe is running on 

Correct
