### ISSUE TITLE
Show test code for results table and remove messaging on probe test page

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#515]
We should show the code in the result table -- then remove it/messaging about pass/fail from the "test" area (top right when you click a result).

**Comment by stephanwampouille** [comment]
Could you provide a little more clarity on this one @kenrick

**Comment by privateducky** [comment]
closing; we need to finalize the scoping of https://github.com/preludeorg/roadmap/issues/76 and I believe this ticket will fall out of scope.
