### ISSUE TITLE
error upon refreshing page when in anonymous-probe

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/build#526]
reported by @packplusplus , but when using an anonymous account and clicked into a demo probe, a window refresh will cause an error because it does not take you back to /probe and during the refresh the account is cleaned up and does not recognize the previous page the probe was associated to.

**Comment by stephanwampouille** [comment]
any first thoughts on how we want to handle this one @kenrick ? If it is an anon user we could redirect them to /probes. I am also thinking this may self resolve with the latest change we made to rename all demo probes to "demo"

**Comment by stephanwampouille** [comment]
have you had anytime to think about this @kenrick ? @ceci21 I'll bring you into this convo too!

**Comment by ceci21** [comment]
@kenrick Is this still an issue? I'm not able to reproduce

**Comment by kenrick** [comment]
yep but its caused by us have anon accounts that gets purged when you refresh. Will need to rethink how work fundementally

**Comment by kenrick** [comment]
will be fixed since we are removing the probe page
