### ISSUE TITLE
Add explanation to statuses in endpoint overlay

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/build#548]
per our convo we should add brief explanations to the following statuses in endpoint overlay:

- PROTECTED
- UNPROTECTED
- REGISTERED
- ERROR

**Comment by stephanwampouille** [comment]
@privateducky do you have any input for this?

**Comment by privateducky** [comment]
Protected=A host is protected if all last test runs came back with an expected response.
Unprotected=A host is unprotected if any test failed on its last run.
Registered=A host is registered if it was provisioned but hasn't run a test yet.
Error=A host is in error if any test threw an exception on its last run.
