### ISSUE TITLE
Add the timezone when formatting timestamps.

### ISSUE THREAD

**Issue by kenrick** [preludeorg/build#618]
across all timestamps, we should indicate the timezone (UTC)

**Comment by kenrick** [comment]
@privateducky so we want to keep timezone in UTC always or use the user's timezone (which is what it does now). We can also show local by default and show the UTC on hover

**Comment by privateducky** [comment]
as long as they're all consistent, all good.. if you show local, we'll have a diff between CLI and UI, so I'd prob opt for sticking with UTC and just relying on the value you get from the BE.

**Comment by privateducky** [comment]
I'm trying to avoid the inevitable: "well, what timezone is it showing me?" questions

**Comment by kenrick** [comment]
Cool will show UTC by default and local on hover
