### ISSUE TITLE
Clarify timestamp on host list

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/build#643]
add context around time stamp here:
<img width="407" alt="Screenshot 2023-02-22 at 1 47 13 PM" src="https://user-images.githubusercontent.com/84744117/220728750-4d81e21d-f4c3-4acf-9c60-748394eb222e.png">

**Comment by stephanwampouille** [comment]
@privateducky do you have any thoughts on this one? I know its part of the "list" but I had also created an issue for it

**Comment by privateducky** [comment]
yeah.... it is currently 'the probes created time'.

**Comment by stephanwampouille** [comment]
would appending "created on ..." satisfy this ticket

**Comment by privateducky** [comment]
yes
