### ISSUE TITLE
Clicking on a rule while account has zero insights removes tests selected

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/build#652]
An account without insights provides this view when clicked into a rule. There is a lack of tests which makes the UI look broken. Do we think we should show the tests applicable under a rule, without putting much thought I am not sure how we accomplish that with the limited data we are provided.

<img width="1469" alt="Screenshot 2023-02-23 at 10 03 44 AM" src="https://user-images.githubusercontent.com/84744117/220945194-0a2824ab-72cf-4626-ba98-b256222f3409.png">

**Comment by stephanwampouille** [comment]
Maybe this is solved when we figure out the rule selector context content

**Comment by kenrick** [comment]
This is expected behavior, because we filter the tests down based on the rule selected we don't want hidden tests to be selected.
